name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:

  test-against-torch-mlir-bindings:

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-11, windows-2022 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install and configure
        shell: bash
        run: |
          pip install .[torch-mlir-test] \
            -f https://github.com/makslevental/mlir-wheels/releases/expanded_assets/latest \
            -f https://llvm.github.io/torch-mlir/package-index/
          if [ ${{ matrix.os }} == 'windows-2022' ]; then
            # configure-mlir-utils.exe -y torch_mlir
            pushd /tmp && python -m mlir_utils._configuration -y torch_mlir && popd
          else
            configure-mlir-utils -y torch_mlir
          fi

      - name: Test
        shell: bash
        run: |
          pytest tests
